apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-demo-app
  template:
    metadata:
      labels:
        app: devops-demo-app
    spec:
      containers:
      - name: devops-demo-container
        image: sampathakkina/demoapp
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: devops-demo-service
spec:
  selector:
    app: devops-demo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080   
  type: NodePort

